## Configuration options to run Autoencoder.py
epochs: 20
transform: "Added ElasticTransform and RandomEqualize"

image_size: 256

model_name: "RESNET50"
optimizer_name: "ADAM"
lr: 0.001
schedule_name: "ReduceLROnPlateau"

network: 
  checkpoint: ~

datasets: 
  train_split: 0.7
  test_split: 0.2
  val_split: 0.10

  train: 
    batch_size: 30

  test:
    batch_size: 30



